### ISSUE TITLE
经验001 三栏网页宽度自适应布局方法

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/css_work_pro#1]
### 绝对定位法
 
html代码
``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
  <div id="left"></div>
  <div id="main"></div>
  <div id="right"></div>
</body>
</html>
```
css代码
``` css
html,body{
  margin: 0;
  height: 100%;
}

#left,#right{
  position: absolute;
  top: 0;
  width: 200px;
  height: 100%;
}

#left{
  left: 0;
  background: #a0b3d6;
}

#right{
  right: 0;
  background: #a0b3d6;
}

#main{
  margin:0 210px;
  background: #ffe6b8;
  height: 100%;
}
```

**Comment by Easy-MJ** [comment]
### margin负值法
html代码
``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>三栏网页宽度自适应布局</title>
</head>
<body>
  <div id="main">
    <div id="body"></div>
  </div>
  <div id="left"></div>
  <div id="right"></div>
</body>
</html>
```
css代码
``` css
html,body{
  margin: 0;
  height: 100%;
}

#main{
  width:100%;
  height:100%;
  float:left;
}

#main #body{
  margin:0 210px;
  background:#ffe6b8;
  height: 100%;
}

#left,#right{
  width:200px;
  height:100%;
  float:left;
  background: #a0b3d6;
}

#left{
  margin-left: -100%;
}

#right{
  margin-left: -200px;
}
```

说明
>首先，中间的主体要使用双层标签。外层div宽度100%显示，并且浮动（本例左浮动，下面所述依次为基础），内层div为真正的主体内容，含有左右210像素的margin值。左栏与右栏都是采用margin负值定位的，左栏左浮动，margin-left为-100%，由于前面的div宽度100%与浏览器，所以这里的-100%margin值正好使左栏div定位到了页面的左侧；右侧栏也是左浮动，其margin-left也是负值，大小为其本身的宽度即200像素。需要注意几个div的顺序，无论是左浮动还是右浮动，先是主体部分div，这是肯定的，至于左右两栏谁先谁后，都无所谓，我测试了IE6，Firefox，以及chrome浏览器，表现一致。

优点
>三栏相互关联，可谓真正意义上的自适应，有一定的抗性——布局不易受内部影响。

缺点
>相对比较难理解些，上手不容易，代码相对复杂。出现百分比宽度，过多的负值定位，如果出现布局的bug，排查不易。

**Comment by Easy-MJ** [comment]
### 自身浮动法
html代码
``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>三栏网页宽度自适应布局</title>
</head>
<body>
  <div id="left"></div>
  <div id="right"></div>
  <div id="main"></div>
</body>
</html>
```
css代码
``` css
html,body{
  margin: 0;
  height: 100%;
}

#main{
  margin:0 210px;
  background:#ffe6b8;
  height: 100%;
}

#left,#right{
  width:200px;
  height:100%;
  float:left;
  background: #a0b3d6;
}

#left{
  float: left;
}

#right{
  float: right;
}
```

说明
>应用了标签浮动跟随的特性。左栏左浮动，右栏右浮动，主体直接放后面，就实现了自适应。这里三个div标签的顺序的关键是要把主体div放在最后，左右两栏div顺序任意。

优点
>代码足够简洁与高效。

缺点
>中间主体存在克星，clear:both属性。如果要使用此方法，需避免明显的clear样式。???
