### ISSUE TITLE
经验002 多张图片并排显示效果并隐藏最后容器的外边距

### ISSUE THREAD

**Issue by Easy-MJ** [Easy-MJ/css_work_pro#2]
html代码
``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>多张图片并排显示效果并隐藏最后容器的外边距</title>
</head>
<body>
  <div class="container">
    <div class="container_wrapper">
      <div class="imgBox"></div>
      <div class="imgBox"></div>
      <div class="imgBox"></div>
      <div class="imgBox"></div>
    </div>
  </div>
</body>
</html>
```
css代码
``` css
body,html,div{
  margin: 0;
  padding: 0;
}

.container{
  width: 830px;
  height: 200px;
  overflow: hidden;
  margin: 0 auto; /*固定宽度容器居中对齐*/
}

.container_wrapper{
  height: 100%;
  margin-right: -10px;
}

.imgBox{
  float: left;
  height: 100%;
  width: 200px;
  margin-right: 10px;
  background: #ccc;
}
```

说明
>外层容器宽度830px，每个imgBox的宽度是200px，margin-right是10px，总共有四个imgBox，
    所以总宽度是840px，最后一个imgBox的margin-right是需要隐藏掉的，因此总宽度是830px，
    技巧是在imgBox外层套一个包装层，该层高度100%，margin-right为负的imgBox的margin-right值，
    这样处理外层div容器的宽度是830px时候就能容纳下四个imgBox。关键点就在于外层的包装层的负margin的使用。
